apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospito-deployment
spec:                     
  replicas: 1
  selector:
    matchLabels:
      app: hospito
  template:
    metadata:
      labels:             
        app: hospito
    spec:                
      containers:
      - name: hospito-containers
        image: yagnik2411/hospito:0.0.1 
        imagePullPolicy: Always
        ports:
        - containerPort: 8080 